-- 코드를 작성해주세요
SELECT B.SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
FROM
    HR_EMPLOYEES A,
    (
        SELECT EMP_NO, SUM(SCORE) AS SCORE
        FROM HR_GRADE
        GROUP BY EMP_NO
    ) B
WHERE A.EMP_NO = B.EMP_NO AND B.SCORE = (
    SELECT MAX(C.SUM_SCORE) FROM (
        SELECT SUM(SCORE) AS SUM_SCORE
        FROM HR_GRADE
        GROUP BY EMP_NO
    ) C
)